version: '2.1'
networks:
  drugstore:
    name: drugstore
    driver: bridge
services:
  product-service:
    container_name: product
    image: drugstore/product-service
    build:
      context: ./product/product-service
      dockerfile: Dockerfile
    ports: [ '8081:8081' ]
    networks: [ drugstore ]
  order-service:
    container_name: order
    image: drugstore/order-service
    build:
      args:
        JDK_VERSION: 8
      context: ./order/order-service
      dockerfile: Dockerfile
    ports: [ '8082:8082' ]
    networks: [ drugstore ]
    depends_on: [ product-service ]


