spring:
  output.ansi.enabled: always
  liquibase.enabled: true
  application.name: drugstore
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db_product:3306/db_product?createDatabaseIfNotExist=true&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    username: admin
    password: admin
    type: com.zaxxer.hikari.HikariDataSource
  liquibase.change-log: classpath:/db/changelog/changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
  cloud:
    stream:
      bindings:
        createProductEventHandler-in-0:
          destination: create.product.event.stream.exchange
          group: ${spring.application.name}@create.product.event.stream.exchange
          consumer:
            bind-queue: true
            requeue-rejected: false
            queue-name-group-only: true
          binder: rabbit
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
product:
  host: ${PRODUCT_HOST:product}
  port: ${PRODUCT_PORT:8081}
order:
  host: ${ORDER_HOST:order}
  port: ${ORDER_PORT:8082}
store:
  host: ${PRODUCT_HOST:store}
  port: ${PRODUCT_PORT:8083}
accountancy:
  host: ${ORDER_HOST:accountancy}
  port: ${ORDER_PORT:8084}
db:
  host: ${DB_HOST:db}
  port: ${DB_PORT:3306}
server:
  port: 8081


