spring:
  output.ansi.enabled: always
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.xml
  application.name: drugstore
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 127.0.0.1
    port: 13020
    url: jdbc:mysql://${spring.datasource.host}:${spring.datasource.port}/db_accountancy?createDatabaseIfNotExist=true&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    username: admin
    password: admin
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
    open-in-view: off
  cloud:
    stream:
      source: createProductEventPublisher
      bindings:
        createProductEventPublisher-out-0:
          destination: create.product.event.stream.exchange
          content-type: application/x-protobuf
        createOutcomeInvoiceEventHandler-in-0:
          destination: create.outcome.invoice.event.stream.exchange
          group: ${spring.application.name}@create.outcome.invoice.event.stream.exchange
          content-type: application/x-protobuf
          consumer:
            bind-queue: true
            requeue-rejected: false
            queue-name-group-only: true
          binder: rabbit
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
product:
  host: ${PRODUCT_HOST:product}
  port: ${PRODUCT_PORT:8081}
order:
  host: ${ORDER_HOST:order}
  port: ${ORDER_PORT:8082}
store:
  host: ${STORE_HOST:store}
  port: ${STORE_PORT:8083}
accountancy:
  host: ${ACCOUNTANCY_HOST:accountancy}
  port: ${ACCOUNTANCY_PORT:8084}
server:
  port: 8084
