// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Api.proto

package sigma.software.leovegas.drugstore.api.protobuf;

public final class AccountancyProto {
  private AccountancyProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface InvoiceDetailsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:sigma.software.leovegas.drugstore.api.InvoiceDetails)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .sigma.software.leovegas.drugstore.api.Item items = 1;</code>
     */
    java.util.List<sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.Item> 
        getItemsList();
    /**
     * <code>repeated .sigma.software.leovegas.drugstore.api.Item items = 1;</code>
     */
    sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.Item getItems(int index);
    /**
     * <code>repeated .sigma.software.leovegas.drugstore.api.Item items = 1;</code>
     */
    int getItemsCount();
    /**
     * <code>repeated .sigma.software.leovegas.drugstore.api.Item items = 1;</code>
     */
    java.util.List<? extends sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.ItemOrBuilder> 
        getItemsOrBuilderList();
    /**
     * <code>repeated .sigma.software.leovegas.drugstore.api.Item items = 1;</code>
     */
    sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.ItemOrBuilder getItemsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code sigma.software.leovegas.drugstore.api.InvoiceDetails}
   */
  public  static final class InvoiceDetails extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:sigma.software.leovegas.drugstore.api.InvoiceDetails)
      InvoiceDetailsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use InvoiceDetails.newBuilder() to construct.
    private InvoiceDetails(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private InvoiceDetails() {
      items_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private InvoiceDetails(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                items_ = new java.util.ArrayList<sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.Item>();
                mutable_bitField0_ |= 0x00000001;
              }
              items_.add(
                  input.readMessage(sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.Item.PARSER, extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          items_ = java.util.Collections.unmodifiableList(items_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.internal_static_sigma_software_leovegas_drugstore_api_InvoiceDetails_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.internal_static_sigma_software_leovegas_drugstore_api_InvoiceDetails_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.InvoiceDetails.class, sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.InvoiceDetails.Builder.class);
    }

    public static final int ITEMS_FIELD_NUMBER = 1;
    private java.util.List<sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.Item> items_;
    /**
     * <code>repeated .sigma.software.leovegas.drugstore.api.Item items = 1;</code>
     */
    public java.util.List<sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.Item> getItemsList() {
      return items_;
    }
    /**
     * <code>repeated .sigma.software.leovegas.drugstore.api.Item items = 1;</code>
     */
    public java.util.List<? extends sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.ItemOrBuilder> 
        getItemsOrBuilderList() {
      return items_;
    }
    /**
     * <code>repeated .sigma.software.leovegas.drugstore.api.Item items = 1;</code>
     */
    public int getItemsCount() {
      return items_.size();
    }
    /**
     * <code>repeated .sigma.software.leovegas.drugstore.api.Item items = 1;</code>
     */
    public sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.Item getItems(int index) {
      return items_.get(index);
    }
    /**
     * <code>repeated .sigma.software.leovegas.drugstore.api.Item items = 1;</code>
     */
    public sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.ItemOrBuilder getItemsOrBuilder(
        int index) {
      return items_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getItemsCount(); i++) {
        if (!getItems(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < items_.size(); i++) {
        output.writeMessage(1, items_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < items_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, items_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.InvoiceDetails)) {
        return super.equals(obj);
      }
      sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.InvoiceDetails other = (sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.InvoiceDetails) obj;

      if (!getItemsList()
          .equals(other.getItemsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getItemsCount() > 0) {
        hash = (37 * hash) + ITEMS_FIELD_NUMBER;
        hash = (53 * hash) + getItemsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.InvoiceDetails parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.InvoiceDetails parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.InvoiceDetails parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.InvoiceDetails parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.InvoiceDetails parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.InvoiceDetails parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.InvoiceDetails parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.InvoiceDetails parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.InvoiceDetails parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.InvoiceDetails parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.InvoiceDetails parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.InvoiceDetails parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.InvoiceDetails prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code sigma.software.leovegas.drugstore.api.InvoiceDetails}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:sigma.software.leovegas.drugstore.api.InvoiceDetails)
        sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.InvoiceDetailsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.internal_static_sigma_software_leovegas_drugstore_api_InvoiceDetails_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.internal_static_sigma_software_leovegas_drugstore_api_InvoiceDetails_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.InvoiceDetails.class, sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.InvoiceDetails.Builder.class);
      }

      // Construct using sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.InvoiceDetails.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getItemsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          itemsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.internal_static_sigma_software_leovegas_drugstore_api_InvoiceDetails_descriptor;
      }

      @java.lang.Override
      public sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.InvoiceDetails getDefaultInstanceForType() {
        return sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.InvoiceDetails.getDefaultInstance();
      }

      @java.lang.Override
      public sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.InvoiceDetails build() {
        sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.InvoiceDetails result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.InvoiceDetails buildPartial() {
        sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.InvoiceDetails result = new sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.InvoiceDetails(this);
        int from_bitField0_ = bitField0_;
        if (itemsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            items_ = java.util.Collections.unmodifiableList(items_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.items_ = items_;
        } else {
          result.items_ = itemsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.InvoiceDetails) {
          return mergeFrom((sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.InvoiceDetails)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.InvoiceDetails other) {
        if (other == sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.InvoiceDetails.getDefaultInstance()) return this;
        if (itemsBuilder_ == null) {
          if (!other.items_.isEmpty()) {
            if (items_.isEmpty()) {
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureItemsIsMutable();
              items_.addAll(other.items_);
            }
            onChanged();
          }
        } else {
          if (!other.items_.isEmpty()) {
            if (itemsBuilder_.isEmpty()) {
              itemsBuilder_.dispose();
              itemsBuilder_ = null;
              items_ = other.items_;
              bitField0_ = (bitField0_ & ~0x00000001);
              itemsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getItemsFieldBuilder() : null;
            } else {
              itemsBuilder_.addAllMessages(other.items_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        for (int i = 0; i < getItemsCount(); i++) {
          if (!getItems(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.InvoiceDetails parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.InvoiceDetails) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.Item> items_ =
        java.util.Collections.emptyList();
      private void ensureItemsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          items_ = new java.util.ArrayList<sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.Item>(items_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.Item, sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.Item.Builder, sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.ItemOrBuilder> itemsBuilder_;

      /**
       * <code>repeated .sigma.software.leovegas.drugstore.api.Item items = 1;</code>
       */
      public java.util.List<sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.Item> getItemsList() {
        if (itemsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(items_);
        } else {
          return itemsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .sigma.software.leovegas.drugstore.api.Item items = 1;</code>
       */
      public int getItemsCount() {
        if (itemsBuilder_ == null) {
          return items_.size();
        } else {
          return itemsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .sigma.software.leovegas.drugstore.api.Item items = 1;</code>
       */
      public sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.Item getItems(int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);
        } else {
          return itemsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .sigma.software.leovegas.drugstore.api.Item items = 1;</code>
       */
      public Builder setItems(
          int index, sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.Item value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.set(index, value);
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .sigma.software.leovegas.drugstore.api.Item items = 1;</code>
       */
      public Builder setItems(
          int index, sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.Item.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.set(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .sigma.software.leovegas.drugstore.api.Item items = 1;</code>
       */
      public Builder addItems(sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.Item value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .sigma.software.leovegas.drugstore.api.Item items = 1;</code>
       */
      public Builder addItems(
          int index, sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.Item value) {
        if (itemsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureItemsIsMutable();
          items_.add(index, value);
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .sigma.software.leovegas.drugstore.api.Item items = 1;</code>
       */
      public Builder addItems(
          sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.Item.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .sigma.software.leovegas.drugstore.api.Item items = 1;</code>
       */
      public Builder addItems(
          int index, sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.Item.Builder builderForValue) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.add(index, builderForValue.build());
          onChanged();
        } else {
          itemsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .sigma.software.leovegas.drugstore.api.Item items = 1;</code>
       */
      public Builder addAllItems(
          java.lang.Iterable<? extends sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.Item> values) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, items_);
          onChanged();
        } else {
          itemsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .sigma.software.leovegas.drugstore.api.Item items = 1;</code>
       */
      public Builder clearItems() {
        if (itemsBuilder_ == null) {
          items_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          itemsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .sigma.software.leovegas.drugstore.api.Item items = 1;</code>
       */
      public Builder removeItems(int index) {
        if (itemsBuilder_ == null) {
          ensureItemsIsMutable();
          items_.remove(index);
          onChanged();
        } else {
          itemsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .sigma.software.leovegas.drugstore.api.Item items = 1;</code>
       */
      public sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.Item.Builder getItemsBuilder(
          int index) {
        return getItemsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .sigma.software.leovegas.drugstore.api.Item items = 1;</code>
       */
      public sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.ItemOrBuilder getItemsOrBuilder(
          int index) {
        if (itemsBuilder_ == null) {
          return items_.get(index);  } else {
          return itemsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .sigma.software.leovegas.drugstore.api.Item items = 1;</code>
       */
      public java.util.List<? extends sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.ItemOrBuilder> 
           getItemsOrBuilderList() {
        if (itemsBuilder_ != null) {
          return itemsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(items_);
        }
      }
      /**
       * <code>repeated .sigma.software.leovegas.drugstore.api.Item items = 1;</code>
       */
      public sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.Item.Builder addItemsBuilder() {
        return getItemsFieldBuilder().addBuilder(
            sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.Item.getDefaultInstance());
      }
      /**
       * <code>repeated .sigma.software.leovegas.drugstore.api.Item items = 1;</code>
       */
      public sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.Item.Builder addItemsBuilder(
          int index) {
        return getItemsFieldBuilder().addBuilder(
            index, sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.Item.getDefaultInstance());
      }
      /**
       * <code>repeated .sigma.software.leovegas.drugstore.api.Item items = 1;</code>
       */
      public java.util.List<sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.Item.Builder> 
           getItemsBuilderList() {
        return getItemsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.Item, sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.Item.Builder, sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.ItemOrBuilder> 
          getItemsFieldBuilder() {
        if (itemsBuilder_ == null) {
          itemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.Item, sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.Item.Builder, sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.ItemOrBuilder>(
                  items_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          items_ = null;
        }
        return itemsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:sigma.software.leovegas.drugstore.api.InvoiceDetails)
    }

    // @@protoc_insertion_point(class_scope:sigma.software.leovegas.drugstore.api.InvoiceDetails)
    private static final sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.InvoiceDetails DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.InvoiceDetails();
    }

    public static sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.InvoiceDetails getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<InvoiceDetails>
        PARSER = new com.google.protobuf.AbstractParser<InvoiceDetails>() {
      @java.lang.Override
      public InvoiceDetails parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new InvoiceDetails(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<InvoiceDetails> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<InvoiceDetails> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.InvoiceDetails getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ItemOrBuilder extends
      // @@protoc_insertion_point(interface_extends:sigma.software.leovegas.drugstore.api.Item)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string productNumber = 1;</code>
     */
    boolean hasProductNumber();
    /**
     * <code>required string productNumber = 1;</code>
     */
    java.lang.String getProductNumber();
    /**
     * <code>required string productNumber = 1;</code>
     */
    com.google.protobuf.ByteString
        getProductNumberBytes();

    /**
     * <code>required int32 quantity = 2;</code>
     */
    boolean hasQuantity();
    /**
     * <code>required int32 quantity = 2;</code>
     */
    int getQuantity();
  }
  /**
   * Protobuf type {@code sigma.software.leovegas.drugstore.api.Item}
   */
  public  static final class Item extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:sigma.software.leovegas.drugstore.api.Item)
      ItemOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Item.newBuilder() to construct.
    private Item(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Item() {
      productNumber_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Item(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              productNumber_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              quantity_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.internal_static_sigma_software_leovegas_drugstore_api_Item_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.internal_static_sigma_software_leovegas_drugstore_api_Item_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.Item.class, sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.Item.Builder.class);
    }

    private int bitField0_;
    public static final int PRODUCTNUMBER_FIELD_NUMBER = 1;
    private volatile java.lang.Object productNumber_;
    /**
     * <code>required string productNumber = 1;</code>
     */
    public boolean hasProductNumber() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string productNumber = 1;</code>
     */
    public java.lang.String getProductNumber() {
      java.lang.Object ref = productNumber_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          productNumber_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string productNumber = 1;</code>
     */
    public com.google.protobuf.ByteString
        getProductNumberBytes() {
      java.lang.Object ref = productNumber_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        productNumber_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int QUANTITY_FIELD_NUMBER = 2;
    private int quantity_;
    /**
     * <code>required int32 quantity = 2;</code>
     */
    public boolean hasQuantity() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required int32 quantity = 2;</code>
     */
    public int getQuantity() {
      return quantity_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasProductNumber()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasQuantity()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, productNumber_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, quantity_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, productNumber_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, quantity_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.Item)) {
        return super.equals(obj);
      }
      sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.Item other = (sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.Item) obj;

      if (hasProductNumber() != other.hasProductNumber()) return false;
      if (hasProductNumber()) {
        if (!getProductNumber()
            .equals(other.getProductNumber())) return false;
      }
      if (hasQuantity() != other.hasQuantity()) return false;
      if (hasQuantity()) {
        if (getQuantity()
            != other.getQuantity()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasProductNumber()) {
        hash = (37 * hash) + PRODUCTNUMBER_FIELD_NUMBER;
        hash = (53 * hash) + getProductNumber().hashCode();
      }
      if (hasQuantity()) {
        hash = (37 * hash) + QUANTITY_FIELD_NUMBER;
        hash = (53 * hash) + getQuantity();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.Item parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.Item parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.Item parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.Item parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.Item parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.Item parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.Item parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.Item parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.Item parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.Item parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.Item parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.Item parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.Item prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code sigma.software.leovegas.drugstore.api.Item}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:sigma.software.leovegas.drugstore.api.Item)
        sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.ItemOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.internal_static_sigma_software_leovegas_drugstore_api_Item_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.internal_static_sigma_software_leovegas_drugstore_api_Item_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.Item.class, sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.Item.Builder.class);
      }

      // Construct using sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.Item.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        productNumber_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        quantity_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.internal_static_sigma_software_leovegas_drugstore_api_Item_descriptor;
      }

      @java.lang.Override
      public sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.Item getDefaultInstanceForType() {
        return sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.Item.getDefaultInstance();
      }

      @java.lang.Override
      public sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.Item build() {
        sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.Item result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.Item buildPartial() {
        sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.Item result = new sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.Item(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.productNumber_ = productNumber_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.quantity_ = quantity_;
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.Item) {
          return mergeFrom((sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.Item)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.Item other) {
        if (other == sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.Item.getDefaultInstance()) return this;
        if (other.hasProductNumber()) {
          bitField0_ |= 0x00000001;
          productNumber_ = other.productNumber_;
          onChanged();
        }
        if (other.hasQuantity()) {
          setQuantity(other.getQuantity());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasProductNumber()) {
          return false;
        }
        if (!hasQuantity()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.Item parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.Item) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object productNumber_ = "";
      /**
       * <code>required string productNumber = 1;</code>
       */
      public boolean hasProductNumber() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required string productNumber = 1;</code>
       */
      public java.lang.String getProductNumber() {
        java.lang.Object ref = productNumber_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            productNumber_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string productNumber = 1;</code>
       */
      public com.google.protobuf.ByteString
          getProductNumberBytes() {
        java.lang.Object ref = productNumber_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          productNumber_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string productNumber = 1;</code>
       */
      public Builder setProductNumber(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        productNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string productNumber = 1;</code>
       */
      public Builder clearProductNumber() {
        bitField0_ = (bitField0_ & ~0x00000001);
        productNumber_ = getDefaultInstance().getProductNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required string productNumber = 1;</code>
       */
      public Builder setProductNumberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        productNumber_ = value;
        onChanged();
        return this;
      }

      private int quantity_ ;
      /**
       * <code>required int32 quantity = 2;</code>
       */
      public boolean hasQuantity() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required int32 quantity = 2;</code>
       */
      public int getQuantity() {
        return quantity_;
      }
      /**
       * <code>required int32 quantity = 2;</code>
       */
      public Builder setQuantity(int value) {
        bitField0_ |= 0x00000002;
        quantity_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 quantity = 2;</code>
       */
      public Builder clearQuantity() {
        bitField0_ = (bitField0_ & ~0x00000002);
        quantity_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:sigma.software.leovegas.drugstore.api.Item)
    }

    // @@protoc_insertion_point(class_scope:sigma.software.leovegas.drugstore.api.Item)
    private static final sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.Item DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.Item();
    }

    public static sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.Item getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Item>
        PARSER = new com.google.protobuf.AbstractParser<Item>() {
      @java.lang.Override
      public Item parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Item(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Item> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Item> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public sigma.software.leovegas.drugstore.api.protobuf.AccountancyProto.Item getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sigma_software_leovegas_drugstore_api_InvoiceDetails_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sigma_software_leovegas_drugstore_api_InvoiceDetails_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sigma_software_leovegas_drugstore_api_Item_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sigma_software_leovegas_drugstore_api_Item_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tApi.proto\022%sigma.software.leovegas.dru" +
      "gstore.api\"L\n\016InvoiceDetails\022:\n\005items\030\001 " +
      "\003(\0132+.sigma.software.leovegas.drugstore." +
      "api.Item\"/\n\004Item\022\025\n\rproductNumber\030\001 \002(\t\022" +
      "\020\n\010quantity\030\002 \002(\005BB\n.sigma.software.leov" +
      "egas.drugstore.api.protobufB\020Accountancy" +
      "Proto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_sigma_software_leovegas_drugstore_api_InvoiceDetails_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_sigma_software_leovegas_drugstore_api_InvoiceDetails_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sigma_software_leovegas_drugstore_api_InvoiceDetails_descriptor,
        new java.lang.String[] { "Items", });
    internal_static_sigma_software_leovegas_drugstore_api_Item_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_sigma_software_leovegas_drugstore_api_Item_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sigma_software_leovegas_drugstore_api_Item_descriptor,
        new java.lang.String[] { "ProductNumber", "Quantity", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
