// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Price.proto

package sigma.software.leovegas.drugstore.api.protobuf;

public final class ProtoProductsPrice {
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_sigma_software_leovegas_drugstore_api_ProductsPrice_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_sigma_software_leovegas_drugstore_api_ProductsPrice_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_sigma_software_leovegas_drugstore_api_ProductsPrice_ItemsEntry_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_sigma_software_leovegas_drugstore_api_ProductsPrice_ItemsEntry_fieldAccessorTable;
    private static final com.google.protobuf.Descriptors.Descriptor
            internal_static_sigma_software_leovegas_drugstore_api_DecimalValue_descriptor;
    private static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_sigma_software_leovegas_drugstore_api_DecimalValue_fieldAccessorTable;
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\013Price.proto\022%sigma.software.leovegas.d" +
                        "rugstore.api\"\302\001\n\rProductsPrice\022N\n\005items\030" +
                        "\001 \003(\0132?.sigma.software.leovegas.drugstor" +
                        "e.api.ProductsPrice.ItemsEntry\032a\n\nItemsE" +
                        "ntry\022\013\n\003key\030\001 \001(\t\022B\n\005value\030\002 \001(\01323.sigma" +
                        ".software.leovegas.drugstore.api.Decimal" +
                        "Value:\0028\001\"?\n\014DecimalValue\022\r\n\005scale\030\001 \001(\r" +
                        "\022\021\n\tprecision\030\002 \001(\r\022\r\n\005value\030\003 \001(\014BD\n.si" +
                        "gma.software.leovegas.drugstore.api.prot" +
                        "obufB\022ProtoProductsPrice"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_sigma_software_leovegas_drugstore_api_ProductsPrice_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_sigma_software_leovegas_drugstore_api_ProductsPrice_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_sigma_software_leovegas_drugstore_api_ProductsPrice_descriptor,
                new java.lang.String[]{"Items",});
        internal_static_sigma_software_leovegas_drugstore_api_ProductsPrice_ItemsEntry_descriptor =
                internal_static_sigma_software_leovegas_drugstore_api_ProductsPrice_descriptor.getNestedTypes().get(0);
        internal_static_sigma_software_leovegas_drugstore_api_ProductsPrice_ItemsEntry_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_sigma_software_leovegas_drugstore_api_ProductsPrice_ItemsEntry_descriptor,
                new java.lang.String[]{"Key", "Value",});
        internal_static_sigma_software_leovegas_drugstore_api_DecimalValue_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_sigma_software_leovegas_drugstore_api_DecimalValue_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_sigma_software_leovegas_drugstore_api_DecimalValue_descriptor,
                new java.lang.String[]{"Scale", "Precision", "Value",});
    }
    private ProtoProductsPrice() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }
    public interface ProductsPriceOrBuilder extends
            // @@protoc_insertion_point(interface_extends:sigma.software.leovegas.drugstore.api.ProductsPrice)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>map&lt;string, .sigma.software.leovegas.drugstore.api.DecimalValue&gt; items = 1;</code>
         */
        int getItemsCount();

        /**
         * <code>map&lt;string, .sigma.software.leovegas.drugstore.api.DecimalValue&gt; items = 1;</code>
         */
        boolean containsItems(
                java.lang.String key);

        /**
         * Use {@link #getItemsMap()} instead.
         */
        @java.lang.Deprecated
        java.util.Map<java.lang.String, sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.DecimalValue>
        getItems();

        /**
         * <code>map&lt;string, .sigma.software.leovegas.drugstore.api.DecimalValue&gt; items = 1;</code>
         */
        java.util.Map<java.lang.String, sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.DecimalValue>
        getItemsMap();

        /**
         * <code>map&lt;string, .sigma.software.leovegas.drugstore.api.DecimalValue&gt; items = 1;</code>
         */

        sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.DecimalValue getItemsOrDefault(
                java.lang.String key,
                sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.DecimalValue defaultValue);

        /**
         * <code>map&lt;string, .sigma.software.leovegas.drugstore.api.DecimalValue&gt; items = 1;</code>
         */

        sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.DecimalValue getItemsOrThrow(
                java.lang.String key);
    }

    public interface DecimalValueOrBuilder extends
            // @@protoc_insertion_point(interface_extends:sigma.software.leovegas.drugstore.api.DecimalValue)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>optional uint32 scale = 1;</code>
         */
        boolean hasScale();

        /**
         * <code>optional uint32 scale = 1;</code>
         */
        int getScale();

        /**
         * <code>optional uint32 precision = 2;</code>
         */
        boolean hasPrecision();

        /**
         * <code>optional uint32 precision = 2;</code>
         */
        int getPrecision();

        /**
         * <code>optional bytes value = 3;</code>
         */
        boolean hasValue();

        /**
         * <code>optional bytes value = 3;</code>
         */
        com.google.protobuf.ByteString getValue();
    }

    /**
     * Protobuf type {@code sigma.software.leovegas.drugstore.api.ProductsPrice}
     */
    public static final class ProductsPrice extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:sigma.software.leovegas.drugstore.api.ProductsPrice)
            ProductsPriceOrBuilder {
        public static final int ITEMS_FIELD_NUMBER = 1;
        @java.lang.Deprecated
        public static final com.google.protobuf.Parser<ProductsPrice>
                PARSER = new com.google.protobuf.AbstractParser<ProductsPrice>() {
            @java.lang.Override
            public ProductsPrice parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new ProductsPrice(input, extensionRegistry);
            }
        };
        private static final long serialVersionUID = 0L;
        // @@protoc_insertion_point(class_scope:sigma.software.leovegas.drugstore.api.ProductsPrice)
        private static final sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.ProductsPrice DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.ProductsPrice();
        }

        private com.google.protobuf.MapField<
                java.lang.String, sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.DecimalValue> items_;
        private byte memoizedIsInitialized = -1;

        // Use ProductsPrice.newBuilder() to construct.
        private ProductsPrice(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }

        private ProductsPrice() {
        }

        private ProductsPrice(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                                items_ = com.google.protobuf.MapField.newMapField(
                                        ItemsDefaultEntryHolder.defaultEntry);
                                mutable_bitField0_ |= 0x00000001;
                            }
                            com.google.protobuf.MapEntry<java.lang.String, sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.DecimalValue>
                                    items__ = input.readMessage(
                                    ItemsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                            items_.getMutableMap().put(
                                    items__.getKey(), items__.getValue());
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.internal_static_sigma_software_leovegas_drugstore_api_ProductsPrice_descriptor;
        }

        public static sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.ProductsPrice parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.ProductsPrice parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.ProductsPrice parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.ProductsPrice parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.ProductsPrice parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.ProductsPrice parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.ProductsPrice parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.ProductsPrice parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.ProductsPrice parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.ProductsPrice parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.ProductsPrice parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.ProductsPrice parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.ProductsPrice prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public static sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.ProductsPrice getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        public static com.google.protobuf.Parser<ProductsPrice> parser() {
            return PARSER;
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        @SuppressWarnings({"rawtypes"})
        @java.lang.Override
        protected com.google.protobuf.MapField internalGetMapField(
                int number) {
            switch (number) {
                case 1:
                    return internalGetItems();
                default:
                    throw new RuntimeException(
                            "Invalid map field number: " + number);
            }
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.internal_static_sigma_software_leovegas_drugstore_api_ProductsPrice_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.ProductsPrice.class, sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.ProductsPrice.Builder.class);
        }

        private com.google.protobuf.MapField<java.lang.String, sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.DecimalValue>
        internalGetItems() {
            if (items_ == null) {
                return com.google.protobuf.MapField.emptyMapField(
                        ItemsDefaultEntryHolder.defaultEntry);
            }
            return items_;
        }

        public int getItemsCount() {
            return internalGetItems().getMap().size();
        }

        /**
         * <code>map&lt;string, .sigma.software.leovegas.drugstore.api.DecimalValue&gt; items = 1;</code>
         */

        public boolean containsItems(
                java.lang.String key) {
            if (key == null) {
                throw new java.lang.NullPointerException();
            }
            return internalGetItems().getMap().containsKey(key);
        }

        /**
         * Use {@link #getItemsMap()} instead.
         */
        @java.lang.Deprecated
        public java.util.Map<java.lang.String, sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.DecimalValue> getItems() {
            return getItemsMap();
        }

        /**
         * <code>map&lt;string, .sigma.software.leovegas.drugstore.api.DecimalValue&gt; items = 1;</code>
         */

        public java.util.Map<java.lang.String, sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.DecimalValue> getItemsMap() {
            return internalGetItems().getMap();
        }

        /**
         * <code>map&lt;string, .sigma.software.leovegas.drugstore.api.DecimalValue&gt; items = 1;</code>
         */

        public sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.DecimalValue getItemsOrDefault(
                java.lang.String key,
                sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.DecimalValue defaultValue) {
            if (key == null) {
                throw new java.lang.NullPointerException();
            }
            java.util.Map<java.lang.String, sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.DecimalValue> map =
                    internalGetItems().getMap();
            return map.containsKey(key) ? map.get(key) : defaultValue;
        }

        /**
         * <code>map&lt;string, .sigma.software.leovegas.drugstore.api.DecimalValue&gt; items = 1;</code>
         */

        public sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.DecimalValue getItemsOrThrow(
                java.lang.String key) {
            if (key == null) {
                throw new java.lang.NullPointerException();
            }
            java.util.Map<java.lang.String, sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.DecimalValue> map =
                    internalGetItems().getMap();
            if (!map.containsKey(key)) {
                throw new java.lang.IllegalArgumentException();
            }
            return map.get(key);
        }

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            com.google.protobuf.GeneratedMessageV3
                    .serializeStringMapTo(
                            output,
                            internalGetItems(),
                            ItemsDefaultEntryHolder.defaultEntry,
                            1);
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            for (java.util.Map.Entry<java.lang.String, sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.DecimalValue> entry
                    : internalGetItems().getMap().entrySet()) {
                com.google.protobuf.MapEntry<java.lang.String, sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.DecimalValue>
                        items__ = ItemsDefaultEntryHolder.defaultEntry.newBuilderForType()
                        .setKey(entry.getKey())
                        .setValue(entry.getValue())
                        .build();
                size += com.google.protobuf.CodedOutputStream
                        .computeMessageSize(1, items__);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.ProductsPrice)) {
                return super.equals(obj);
            }
            sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.ProductsPrice other = (sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.ProductsPrice) obj;

            if (!internalGetItems().equals(
                    other.internalGetItems())) return false;
            if (!unknownFields.equals(other.unknownFields)) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (!internalGetItems().getMap().isEmpty()) {
                hash = (37 * hash) + ITEMS_FIELD_NUMBER;
                hash = (53 * hash) + internalGetItems().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<ProductsPrice> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.ProductsPrice getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

        private static final class ItemsDefaultEntryHolder {
            static final com.google.protobuf.MapEntry<
                    java.lang.String, sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.DecimalValue> defaultEntry =
                    com.google.protobuf.MapEntry
                            .<java.lang.String, sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.DecimalValue>newDefaultInstance(
                                    sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.internal_static_sigma_software_leovegas_drugstore_api_ProductsPrice_ItemsEntry_descriptor,
                                    com.google.protobuf.WireFormat.FieldType.STRING,
                                    "",
                                    com.google.protobuf.WireFormat.FieldType.MESSAGE,
                                    sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.DecimalValue.getDefaultInstance());
        }

        /**
         * Protobuf type {@code sigma.software.leovegas.drugstore.api.ProductsPrice}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:sigma.software.leovegas.drugstore.api.ProductsPrice)
                sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.ProductsPriceOrBuilder {
            private int bitField0_;
            private com.google.protobuf.MapField<
                    java.lang.String, sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.DecimalValue> items_;

            // Construct using sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.ProductsPrice.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.internal_static_sigma_software_leovegas_drugstore_api_ProductsPrice_descriptor;
            }

            @SuppressWarnings({"rawtypes"})
            protected com.google.protobuf.MapField internalGetMapField(
                    int number) {
                switch (number) {
                    case 1:
                        return internalGetItems();
                    default:
                        throw new RuntimeException(
                                "Invalid map field number: " + number);
                }
            }

            @SuppressWarnings({"rawtypes"})
            protected com.google.protobuf.MapField internalGetMutableMapField(
                    int number) {
                switch (number) {
                    case 1:
                        return internalGetMutableItems();
                    default:
                        throw new RuntimeException(
                                "Invalid map field number: " + number);
                }
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.internal_static_sigma_software_leovegas_drugstore_api_ProductsPrice_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.ProductsPrice.class, sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.ProductsPrice.Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                internalGetMutableItems().clear();
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.internal_static_sigma_software_leovegas_drugstore_api_ProductsPrice_descriptor;
            }

            @java.lang.Override
            public sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.ProductsPrice getDefaultInstanceForType() {
                return sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.ProductsPrice.getDefaultInstance();
            }

            @java.lang.Override
            public sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.ProductsPrice build() {
                sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.ProductsPrice result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.ProductsPrice buildPartial() {
                sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.ProductsPrice result = new sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.ProductsPrice(this);
                int from_bitField0_ = bitField0_;
                result.items_ = internalGetItems();
                result.items_.makeImmutable();
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.ProductsPrice) {
                    return mergeFrom((sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.ProductsPrice) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.ProductsPrice other) {
                if (other == sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.ProductsPrice.getDefaultInstance())
                    return this;
                internalGetMutableItems().mergeFrom(
                        other.internalGetItems());
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.ProductsPrice parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.ProductsPrice) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private com.google.protobuf.MapField<java.lang.String, sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.DecimalValue>
            internalGetItems() {
                if (items_ == null) {
                    return com.google.protobuf.MapField.emptyMapField(
                            ItemsDefaultEntryHolder.defaultEntry);
                }
                return items_;
            }

            private com.google.protobuf.MapField<java.lang.String, sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.DecimalValue>
            internalGetMutableItems() {
                onChanged();
                ;
                if (items_ == null) {
                    items_ = com.google.protobuf.MapField.newMapField(
                            ItemsDefaultEntryHolder.defaultEntry);
                }
                if (!items_.isMutable()) {
                    items_ = items_.copy();
                }
                return items_;
            }

            public int getItemsCount() {
                return internalGetItems().getMap().size();
            }

            /**
             * <code>map&lt;string, .sigma.software.leovegas.drugstore.api.DecimalValue&gt; items = 1;</code>
             */

            public boolean containsItems(
                    java.lang.String key) {
                if (key == null) {
                    throw new java.lang.NullPointerException();
                }
                return internalGetItems().getMap().containsKey(key);
            }

            /**
             * Use {@link #getItemsMap()} instead.
             */
            @java.lang.Deprecated
            public java.util.Map<java.lang.String, sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.DecimalValue> getItems() {
                return getItemsMap();
            }

            /**
             * <code>map&lt;string, .sigma.software.leovegas.drugstore.api.DecimalValue&gt; items = 1;</code>
             */

            public java.util.Map<java.lang.String, sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.DecimalValue> getItemsMap() {
                return internalGetItems().getMap();
            }

            /**
             * <code>map&lt;string, .sigma.software.leovegas.drugstore.api.DecimalValue&gt; items = 1;</code>
             */

            public sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.DecimalValue getItemsOrDefault(
                    java.lang.String key,
                    sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.DecimalValue defaultValue) {
                if (key == null) {
                    throw new java.lang.NullPointerException();
                }
                java.util.Map<java.lang.String, sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.DecimalValue> map =
                        internalGetItems().getMap();
                return map.containsKey(key) ? map.get(key) : defaultValue;
            }

            /**
             * <code>map&lt;string, .sigma.software.leovegas.drugstore.api.DecimalValue&gt; items = 1;</code>
             */

            public sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.DecimalValue getItemsOrThrow(
                    java.lang.String key) {
                if (key == null) {
                    throw new java.lang.NullPointerException();
                }
                java.util.Map<java.lang.String, sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.DecimalValue> map =
                        internalGetItems().getMap();
                if (!map.containsKey(key)) {
                    throw new java.lang.IllegalArgumentException();
                }
                return map.get(key);
            }

            public Builder clearItems() {
                internalGetMutableItems().getMutableMap()
                        .clear();
                return this;
            }

            /**
             * <code>map&lt;string, .sigma.software.leovegas.drugstore.api.DecimalValue&gt; items = 1;</code>
             */

            public Builder removeItems(
                    java.lang.String key) {
                if (key == null) {
                    throw new java.lang.NullPointerException();
                }
                internalGetMutableItems().getMutableMap()
                        .remove(key);
                return this;
            }

            /**
             * Use alternate mutation accessors instead.
             */
            @java.lang.Deprecated
            public java.util.Map<java.lang.String, sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.DecimalValue>
            getMutableItems() {
                return internalGetMutableItems().getMutableMap();
            }

            /**
             * <code>map&lt;string, .sigma.software.leovegas.drugstore.api.DecimalValue&gt; items = 1;</code>
             */
            public Builder putItems(
                    java.lang.String key,
                    sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.DecimalValue value) {
                if (key == null) {
                    throw new java.lang.NullPointerException();
                }
                if (value == null) {
                    throw new java.lang.NullPointerException();
                }
                internalGetMutableItems().getMutableMap()
                        .put(key, value);
                return this;
            }

            /**
             * <code>map&lt;string, .sigma.software.leovegas.drugstore.api.DecimalValue&gt; items = 1;</code>
             */

            public Builder putAllItems(
                    java.util.Map<java.lang.String, sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.DecimalValue> values) {
                internalGetMutableItems().getMutableMap()
                        .putAll(values);
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:sigma.software.leovegas.drugstore.api.ProductsPrice)
        }

    }

    /**
     * Protobuf type {@code sigma.software.leovegas.drugstore.api.DecimalValue}
     */
    public static final class DecimalValue extends
            com.google.protobuf.GeneratedMessageV3 implements
            // @@protoc_insertion_point(message_implements:sigma.software.leovegas.drugstore.api.DecimalValue)
            DecimalValueOrBuilder {
        public static final int SCALE_FIELD_NUMBER = 1;
        public static final int PRECISION_FIELD_NUMBER = 2;
        public static final int VALUE_FIELD_NUMBER = 3;
        @java.lang.Deprecated
        public static final com.google.protobuf.Parser<DecimalValue>
                PARSER = new com.google.protobuf.AbstractParser<DecimalValue>() {
            @java.lang.Override
            public DecimalValue parsePartialFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                return new DecimalValue(input, extensionRegistry);
            }
        };
        private static final long serialVersionUID = 0L;
        // @@protoc_insertion_point(class_scope:sigma.software.leovegas.drugstore.api.DecimalValue)
        private static final sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.DecimalValue DEFAULT_INSTANCE;

        static {
            DEFAULT_INSTANCE = new sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.DecimalValue();
        }

        private int bitField0_;
        private int scale_;
        private int precision_;
        private com.google.protobuf.ByteString value_;
        private byte memoizedIsInitialized = -1;

        // Use DecimalValue.newBuilder() to construct.
        private DecimalValue(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
            super(builder);
        }
        private DecimalValue() {
            value_ = com.google.protobuf.ByteString.EMPTY;
        }

        private DecimalValue(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            this();
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            int mutable_bitField0_ = 0;
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                    com.google.protobuf.UnknownFieldSet.newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 8: {
                            bitField0_ |= 0x00000001;
                            scale_ = input.readUInt32();
                            break;
                        }
                        case 16: {
                            bitField0_ |= 0x00000002;
                            precision_ = input.readUInt32();
                            break;
                        }
                        case 26: {
                            bitField0_ |= 0x00000004;
                            value_ = input.readBytes();
                            break;
                        }
                        default: {
                            if (!parseUnknownField(
                                    input, unknownFields, extensionRegistry, tag)) {
                                done = true;
                            }
                            break;
                        }
                    }
                }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(this);
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(
                        e).setUnfinishedMessage(this);
            } finally {
                this.unknownFields = unknownFields.build();
                makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.internal_static_sigma_software_leovegas_drugstore_api_DecimalValue_descriptor;
        }

        public static sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.DecimalValue parseFrom(
                java.nio.ByteBuffer data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.DecimalValue parseFrom(
                java.nio.ByteBuffer data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.DecimalValue parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.DecimalValue parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.DecimalValue parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data);
        }

        public static sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.DecimalValue parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return PARSER.parseFrom(data, extensionRegistry);
        }

        public static sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.DecimalValue parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.DecimalValue parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.DecimalValue parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input);
        }

        public static sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.DecimalValue parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
        }

        public static sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.DecimalValue parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input);
        }

        public static sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.DecimalValue parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return com.google.protobuf.GeneratedMessageV3
                    .parseWithIOException(PARSER, input, extensionRegistry);
        }

        public static Builder newBuilder() {
            return DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.DecimalValue prototype) {
            return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        public static sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.DecimalValue getDefaultInstance() {
            return DEFAULT_INSTANCE;
        }

        public static com.google.protobuf.Parser<DecimalValue> parser() {
            return PARSER;
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
            return this.unknownFields;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.internal_static_sigma_software_leovegas_drugstore_api_DecimalValue_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.DecimalValue.class, sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.DecimalValue.Builder.class);
        }

        /**
         * <code>optional uint32 scale = 1;</code>
         */
        public boolean hasScale() {
            return ((bitField0_ & 0x00000001) != 0);
        }

        /**
         * <code>optional uint32 scale = 1;</code>
         */
        public int getScale() {
            return scale_;
        }

        /**
         * <code>optional uint32 precision = 2;</code>
         */
        public boolean hasPrecision() {
            return ((bitField0_ & 0x00000002) != 0);
        }

        /**
         * <code>optional uint32 precision = 2;</code>
         */
        public int getPrecision() {
            return precision_;
        }

        /**
         * <code>optional bytes value = 3;</code>
         */
        public boolean hasValue() {
            return ((bitField0_ & 0x00000004) != 0);
        }

        /**
         * <code>optional bytes value = 3;</code>
         */
        public com.google.protobuf.ByteString getValue() {
            return value_;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized == 1) return true;
            if (isInitialized == 0) return false;

            memoizedIsInitialized = 1;
            return true;
        }

        @java.lang.Override
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            if (((bitField0_ & 0x00000001) != 0)) {
                output.writeUInt32(1, scale_);
            }
            if (((bitField0_ & 0x00000002) != 0)) {
                output.writeUInt32(2, precision_);
            }
            if (((bitField0_ & 0x00000004) != 0)) {
                output.writeBytes(3, value_);
            }
            unknownFields.writeTo(output);
        }

        @java.lang.Override
        public int getSerializedSize() {
            int size = memoizedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) != 0)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt32Size(1, scale_);
            }
            if (((bitField0_ & 0x00000002) != 0)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeUInt32Size(2, precision_);
            }
            if (((bitField0_ & 0x00000004) != 0)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(3, value_);
            }
            size += unknownFields.getSerializedSize();
            memoizedSize = size;
            return size;
        }

        @java.lang.Override
        public boolean equals(final java.lang.Object obj) {
            if (obj == this) {
                return true;
            }
            if (!(obj instanceof sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.DecimalValue)) {
                return super.equals(obj);
            }
            sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.DecimalValue other = (sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.DecimalValue) obj;

            if (hasScale() != other.hasScale()) return false;
            if (hasScale()) {
                if (getScale()
                        != other.getScale()) return false;
            }
            if (hasPrecision() != other.hasPrecision()) return false;
            if (hasPrecision()) {
                if (getPrecision()
                        != other.getPrecision()) return false;
            }
            if (hasValue() != other.hasValue()) return false;
            if (hasValue()) {
                if (!getValue()
                        .equals(other.getValue())) return false;
            }
            if (!unknownFields.equals(other.unknownFields)) return false;
            return true;
        }

        @java.lang.Override
        public int hashCode() {
            if (memoizedHashCode != 0) {
                return memoizedHashCode;
            }
            int hash = 41;
            hash = (19 * hash) + getDescriptor().hashCode();
            if (hasScale()) {
                hash = (37 * hash) + SCALE_FIELD_NUMBER;
                hash = (53 * hash) + getScale();
            }
            if (hasPrecision()) {
                hash = (37 * hash) + PRECISION_FIELD_NUMBER;
                hash = (53 * hash) + getPrecision();
            }
            if (hasValue()) {
                hash = (37 * hash) + VALUE_FIELD_NUMBER;
                hash = (53 * hash) + getValue().hashCode();
            }
            hash = (29 * hash) + unknownFields.hashCode();
            memoizedHashCode = hash;
            return hash;
        }

        @java.lang.Override
        public Builder newBuilderForType() {
            return newBuilder();
        }

        @java.lang.Override
        public Builder toBuilder() {
            return this == DEFAULT_INSTANCE
                    ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<DecimalValue> getParserForType() {
            return PARSER;
        }

        @java.lang.Override
        public sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.DecimalValue getDefaultInstanceForType() {
            return DEFAULT_INSTANCE;
        }

        /**
         * Protobuf type {@code sigma.software.leovegas.drugstore.api.DecimalValue}
         */
        public static final class Builder extends
                com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:sigma.software.leovegas.drugstore.api.DecimalValue)
                sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.DecimalValueOrBuilder {
            private int bitField0_;
            private int scale_;
            private int precision_;
            private com.google.protobuf.ByteString value_ = com.google.protobuf.ByteString.EMPTY;

            // Construct using sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.DecimalValue.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(
                    com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }

            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.internal_static_sigma_software_leovegas_drugstore_api_DecimalValue_descriptor;
            }

            @java.lang.Override
            protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.internal_static_sigma_software_leovegas_drugstore_api_DecimalValue_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(
                                sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.DecimalValue.class, sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.DecimalValue.Builder.class);
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessageV3
                        .alwaysUseFieldBuilders) {
                }
            }

            @java.lang.Override
            public Builder clear() {
                super.clear();
                scale_ = 0;
                bitField0_ = (bitField0_ & ~0x00000001);
                precision_ = 0;
                bitField0_ = (bitField0_ & ~0x00000002);
                value_ = com.google.protobuf.ByteString.EMPTY;
                bitField0_ = (bitField0_ & ~0x00000004);
                return this;
            }

            @java.lang.Override
            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.internal_static_sigma_software_leovegas_drugstore_api_DecimalValue_descriptor;
            }

            @java.lang.Override
            public sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.DecimalValue getDefaultInstanceForType() {
                return sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.DecimalValue.getDefaultInstance();
            }

            @java.lang.Override
            public sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.DecimalValue build() {
                sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.DecimalValue result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            @java.lang.Override
            public sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.DecimalValue buildPartial() {
                sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.DecimalValue result = new sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.DecimalValue(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) != 0)) {
                    result.scale_ = scale_;
                    to_bitField0_ |= 0x00000001;
                }
                if (((from_bitField0_ & 0x00000002) != 0)) {
                    result.precision_ = precision_;
                    to_bitField0_ |= 0x00000002;
                }
                if (((from_bitField0_ & 0x00000004) != 0)) {
                    to_bitField0_ |= 0x00000004;
                }
                result.value_ = value_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            @java.lang.Override
            public Builder clone() {
                return super.clone();
            }

            @java.lang.Override
            public Builder setField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.setField(field, value);
            }

            @java.lang.Override
            public Builder clearField(
                    com.google.protobuf.Descriptors.FieldDescriptor field) {
                return super.clearField(field);
            }

            @java.lang.Override
            public Builder clearOneof(
                    com.google.protobuf.Descriptors.OneofDescriptor oneof) {
                return super.clearOneof(oneof);
            }

            @java.lang.Override
            public Builder setRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    int index, java.lang.Object value) {
                return super.setRepeatedField(field, index, value);
            }

            @java.lang.Override
            public Builder addRepeatedField(
                    com.google.protobuf.Descriptors.FieldDescriptor field,
                    java.lang.Object value) {
                return super.addRepeatedField(field, value);
            }

            @java.lang.Override
            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.DecimalValue) {
                    return mergeFrom((sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.DecimalValue) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.DecimalValue other) {
                if (other == sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.DecimalValue.getDefaultInstance())
                    return this;
                if (other.hasScale()) {
                    setScale(other.getScale());
                }
                if (other.hasPrecision()) {
                    setPrecision(other.getPrecision());
                }
                if (other.hasValue()) {
                    setValue(other.getValue());
                }
                this.mergeUnknownFields(other.unknownFields);
                onChanged();
                return this;
            }

            @java.lang.Override
            public final boolean isInitialized() {
                return true;
            }

            @java.lang.Override
            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.DecimalValue parsedMessage = null;
                try {
                    parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (sigma.software.leovegas.drugstore.api.protobuf.ProtoProductsPrice.DecimalValue) e.getUnfinishedMessage();
                    throw e.unwrapIOException();
                } finally {
                    if (parsedMessage != null) {
                        mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            /**
             * <code>optional uint32 scale = 1;</code>
             */
            public boolean hasScale() {
                return ((bitField0_ & 0x00000001) != 0);
            }

            /**
             * <code>optional uint32 scale = 1;</code>
             */
            public int getScale() {
                return scale_;
            }

            /**
             * <code>optional uint32 scale = 1;</code>
             */
            public Builder setScale(int value) {
                bitField0_ |= 0x00000001;
                scale_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional uint32 scale = 1;</code>
             */
            public Builder clearScale() {
                bitField0_ = (bitField0_ & ~0x00000001);
                scale_ = 0;
                onChanged();
                return this;
            }

            /**
             * <code>optional uint32 precision = 2;</code>
             */
            public boolean hasPrecision() {
                return ((bitField0_ & 0x00000002) != 0);
            }

            /**
             * <code>optional uint32 precision = 2;</code>
             */
            public int getPrecision() {
                return precision_;
            }

            /**
             * <code>optional uint32 precision = 2;</code>
             */
            public Builder setPrecision(int value) {
                bitField0_ |= 0x00000002;
                precision_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional uint32 precision = 2;</code>
             */
            public Builder clearPrecision() {
                bitField0_ = (bitField0_ & ~0x00000002);
                precision_ = 0;
                onChanged();
                return this;
            }

            /**
             * <code>optional bytes value = 3;</code>
             */
            public boolean hasValue() {
                return ((bitField0_ & 0x00000004) != 0);
            }

            /**
             * <code>optional bytes value = 3;</code>
             */
            public com.google.protobuf.ByteString getValue() {
                return value_;
            }

            /**
             * <code>optional bytes value = 3;</code>
             */
            public Builder setValue(com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000004;
                value_ = value;
                onChanged();
                return this;
            }

            /**
             * <code>optional bytes value = 3;</code>
             */
            public Builder clearValue() {
                bitField0_ = (bitField0_ & ~0x00000004);
                value_ = getDefaultInstance().getValue();
                onChanged();
                return this;
            }

            @java.lang.Override
            public final Builder setUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.setUnknownFields(unknownFields);
            }

            @java.lang.Override
            public final Builder mergeUnknownFields(
                    final com.google.protobuf.UnknownFieldSet unknownFields) {
                return super.mergeUnknownFields(unknownFields);
            }


            // @@protoc_insertion_point(builder_scope:sigma.software.leovegas.drugstore.api.DecimalValue)
        }

    }

    // @@protoc_insertion_point(outer_class_scope)
}
