version: '2.1'
networks:
  drugstore:
    name: drugstore
    driver: bridge
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.6.6-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks: [ drugstore ]
  db_product:
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 12810241024 # 128 mb = 128 * 1024 * 1024
    container_name: db_product
    image: mysql:8.0.26
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: db_product
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports: [ '13008:3306' ]
    networks: [ drugstore ]
    healthcheck:
      retries: 20
      timeout: 40s
      interval: 10s
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "$$MYSQL_USER", "--password=$$MYSQL_PASSWORD" ]
  db_order:
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 12810241024 # 128 mb = 128 * 1024 * 1024
    container_name: db_order
    image: mysql:8.0.26
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: db_order
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports: [ "13017:3306" ]
    networks: [ drugstore ]
    healthcheck:
      retries: 20
      timeout: 40s
      interval: 10s
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "$$MYSQL_USER", "--password=$$MYSQL_PASSWORD" ]
  db_store:
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 12810241024 # 128 mb = 128 * 1024 * 1024
    container_name: db_store
    image: mysql:8.0.26
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: db_store
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports: [ "13029:3306" ]
    networks: [ drugstore ]
    healthcheck:
      retries: 20
      timeout: 40s
      interval: 10s
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "$$MYSQL_USER", "--password=$$MYSQL_PASSWORD" ]
  db_accountancy:
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 12810241024 # 128 mb = 128 * 1024 * 1024
    container_name: db_accountancy
    image: mysql:8.0.26
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: db_accountancy
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports: [ "13020:3306" ]
    networks: [ drugstore ]
    healthcheck:
      retries: 20
      timeout: 40s
      interval: 10s
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost", "-u", "$$MYSQL_USER", "--password=$$MYSQL_PASSWORD" ]
