version: '2.1'
networks:
  drugstore:
    name: drugstore
    driver: bridge
services:
  db_product:
    container_name: db_product
    image: mysql:8.0.26
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: db_product
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports: [ '13008:3306' ]
    networks: [ drugstore ]
    healthcheck:
      retries: 9
      timeout: 20s
      interval: 5s
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
  product-service:
    container_name: product
    restart: on-failure
    image: drugstore/product-service
    build:
      context: ../product/product-service/
      dockerfile: ./Dockerfile
    ports: [ '8081:8081' ]
    networks: [ drugstore ]
    depends_on:
      db_product:
        condition: service_healthy
  db_order:
    container_name: db_order
    image: mysql:8.0.26
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: db_order
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports: [ "13017:3306" ]
    networks: [ drugstore ]
    healthcheck:
      retries: 9
      timeout: 20s
      interval: 5s
      test:  ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
  order-service:
    container_name: order
    image: drugstore/order-service
    restart: on-failure
    build:
      context: ../order/order-service/
      dockerfile: ./Dockerfile
    ports: [ '8082:8082' ]
    networks: [ drugstore ]
    depends_on:
      db_order:
        condition: service_healthy
  db_store:
    container_name: db_store
    image: mysql:8.0.26
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: db_store
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports: [ "13029:3306" ]
    networks: [ drugstore ]
    healthcheck:
      retries: 9
      timeout: 20s
      interval: 5s
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
  store-service:
    container_name: store
    restart: on-failure
    image: drugstore/store-service
    build:
      context: ../store/store-service/
      dockerfile: ./Dockerfile
    ports: [ '8083:8083' ]
    networks: [ drugstore ]
    depends_on:
      db_store:
        condition: service_healthy
  db_accountancy:
    container_name: db_accountancy
    image: mysql:8.0.26
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: db_accountancy
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports: [ "13020:3306" ]
    networks: [ drugstore ]
    healthcheck:
      retries: 9
      timeout: 20s
      interval: 5s
      test:  ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
  accountancy-service:
    container_name: accountancy
    restart: on-failure
    image: drugstore/accountancy-service
    build:
      context: ../accountancy/accountancy-service/
      dockerfile: ./Dockerfile
    ports: [ '8084:8084' ]
    networks: [ drugstore ]
    depends_on:
      db_accountancy:
        condition: service_healthy
