version: '2.1'
networks:
  drugstore:
    name: drugstore
    driver: bridge
services:
  product-service:
    container_name: product
    image: drugstore/product-service
    build:
      context: ../product/product-service/
      dockerfile: ./Dockerfile
    ports: [ '8081:8081' ]
    networks: [ drugstore ]
  order-service:
    container_name: order
    image: drugstore/order-service
    build:
      context: ../order/order-service/
      dockerfile: ./Dockerfile
    ports: [ '8082:8082' ]
    networks: [ drugstore ]
    depends_on: [order-mysql]
#      order-mysql:
#        condition: service_healthy
  order-mysql:
    container_name: order-mysql
    image: mysql:5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: orderpass
      MYSQL_DATABASE: order-service
      MYSQL_USER: orderuser
      MYSQL_PASSWORD: orderpass
    ports: [ "3306:3306" ]
    networks: [ drugstore ]
#    healthcheck:
#      retries: 9
#      timeout: 3s
#      interval: 3s
#      test: [ "CMD", "mysqladmin" ,"ping", "-h", "127.0.0.2" ]
  store-service:
    container_name: store
    image: drugstore/store-service
    build:
      context: ../store/store-service/
      dockerfile: ./Dockerfile
    ports: [ '8083:8083' ]
    networks: [ drugstore ]
  accountancy-service:
    container_name: accountancy
    image: drugstore/accountancy-service
    build:
      context: ../accountancy/accountancy-service/
      dockerfile: ./Dockerfile
    ports: [ '8084:8084' ]
    networks: [ drugstore ]
